palette = "noctalia"
add_newline = false

format = """
$hostname$username$directory$git_branch$cmd_duration
$env_var"""

[env_var.STARSHIP_SHELL]
format = '[](bold fg:green)[$env_value](bold bg:green)[](bold fg:green)'
disabled = false

[git_branch]
symbol = "󰘬"
format = "[](bold fg:green)[$symbol $branch(:$remote_branch)](fg:text bg:green)[](bold fg:green)"

[git_commit]
commit_hash_length = 4
tag_symbol = "  "

[git_status]
conflicted = " 🏳 "
ahead = " 🏎💨 "
behind = " 😰 "
diverged = " 😵 "
untracked = " 🤷 ‍"
stashed = " 📦 "
modified = " 📝 "
staged = '[++\($count\)](green)'
renamed = " ✍️ "
deleted = " 🗑 "

[hostname]
ssh_only = false
format =  "[](bold fg:green)[$hostname](bg:green bold fg:text)[@](bold bg:green fg:text)"
trim_at = ".companyname.com"
disabled = false

[username]
format = "[](bold)[$user](bold fg:text bg:green)[](bold fg:green)"
disabled = false
show_always = true

[directory]
home_symbol = ""
read_only = ""
truncation_length = 2
truncation_symbol = ".../"
format = '[](bold fg:green)[$path](bold fg:text bg:green)[](bold fg:green)'

[directory.substitutions]
"Рабочий стол" = ""
"Документы" = "󰈙"
"Загрузки" = ""
"Музыка" = ""
"Изображения" = ""
"Видео" = ""
"GitHub" = "󰊤"
"Игры" = ""
"Общедоступные" = "󰀃"
"Проекты" = "󰐯"
"Шаблоны" = ""
".config" = ""
".icons" = ""

[cmd_duration]
min_time = 0
format = '[](bold fg:green)[ $duration](bold bg:green fg:text)[](bold fg:green)'
disabled = false

# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#9071f4"
red       = "#f9515d"
green     = "#37f499"
yellow    = "#e9f941"
cyan      = "#04d1f9"
magenta   = "#f265b5"
white     = "#ebfafa"
black     = "#21222c"

# Extended palette (Catppuccin-compatible names)
rosewater = "#f1fc79"
flamingo  = "#f16c75"
pink      = "#fd92ce"
mauve     = "#f265b5"
maroon    = "#f16c75"
peach     = "#f1fc79"
teal      = "#04d1f9"
sky       = "#66e4fd"
sapphire  = "#a48cf2"
lavender  = "#fd92ce"

# Text shades
text      = "#ebfafa"
subtext1  = "#ebfafa"
subtext0  = "#7081d0"

# Surface shades
overlay2  = "#7081d0"
overlay1  = "#7081d0"
overlay0  = "#21222c"
surface2  = "#21222c"
surface1  = "#21222c"
surface0  = "#212337"
base      = "#212337"
mantle    = "#212337"
crust     = "#212337"
# <<< NOCTALIA STARSHIP PALETTE <<<
