[colors]
background = "#313244FF"
text_primary = "#cdd6f4FF"
text_muted = "#a6adc8FF"
accent_primary = "#89b4faFF"
accent_secondary = "#b4befeFF"
warning = "#cba6f7FF"
error = "#f38ba8FF"
insert_hint = "#cba6f780"
backdrop = "#313244FF"

[colors.border]
focused = "#89b4faFF"
unfocused = "#313244FF"
scratchpad_focused = "#cba6f7FF"
scratchpad_unfocused = "#6d10daFF"
outer = "#1e1e2eFF"

[colors.overview]
background_tint = "#1e1e2e88"
badge = "#89b4faFF"
workspace_background = "#1e1e2eFF"
