-- NOTE: Hyprland main config file
require("modules.env")
require("modules.bind")
require("modules.misc")
require("modules.input")
require("modules.cursor")
require("modules.device")
require("modules.gesture")
require("modules.dwindle")
require("modules.monitor")
require("modules.general")
require("modules.xwayland")
require("modules.ecosystem")
require("modules.autostart")
require("modules.decoration")
require("modules.animations")
require("modules.window-rule")
