-- NOTE: Hyprland main config file
require("modules.env")
require("modules.bind")
require("modules.misc")
require("modules.input")
require("modules.debug")
require("modules.cursor")
require("modules.device")
require("modules.gesture")
require("modules.dwindle")
require("modules.monitor")
require("modules.general")
require("modules.xwayland")
require("modules.ecosystem")
require("modules.autostart")
require("modules.workspaces")
require("modules.decoration")
require("modules.animations")
require("modules.window-rule")

-- NOTE: Plugins
require("plugins.hyprcapture")
require("plugins.scroll-overview")
require("plugins.hypr-dynamic-cursors")
