-- NOTE: `Hyprland` workspaces config file
hl.workspace_rule({ workspace = "1", default_name = "1", persistent = true })
hl.workspace_rule({ workspace = "2", default_name = "2", persistent = true })
hl.workspace_rule({ workspace = "3", default_name = "3", persistent = true })
hl.workspace_rule({ workspace = "4", default_name = "4", persistent = true })
hl.workspace_rule({ workspace = "5", default_name = "5", persistent = true })
hl.workspace_rule({ workspace = "6", default_name = "6", persistent = true })
hl.workspace_rule({ workspace = "7", default_name = "7", persistent = true })
hl.workspace_rule({ workspace = "8", default_name = "8", persistent = true })
hl.workspace_rule({ workspace = "9", default_name = "9", persistent = true })
hl.workspace_rule({ workspace = "10", default_name = "10", persistent = true })
