[animation]
enabled = true

[animation.beziers]
easeInOutExpo = [0.87, 0, 0.13, 1]
easeInOutQuart = [0.76, 0, 0.24, 1]

[animation.windows_in]
curve = "easeInOutExpo"
duration_ms = 200
enabled = true
style = "fade"

[animation.windows_out]
curve = "easeInOutExpo"
duration_ms = 200
enabled = true

[animation.windows_move]
curve = "easeInOutExpo"
duration_ms = 150
enabled = true

[animation.windows_drag]
physics = false

[animation.workspaces]
curve = "easeInOutExpo"
duration_ms = 200
enabled = true

[animation.overview]
curve = "easeInOutQuart"
duration_ms = 200
enabled = true

[animation.scratchpad]
enabled = true

[animation.border]
enabled = true

[animation.dim_unfocused]
curve = "easeInOutExpo"
duration_ms = 150
enabled = true

[animation.layers]
curve = "easeInOutExpo"
duration_ms = 250
enabled = true