# Umbriel `appearance` config file

[appearance]
prefer_no_csd = true
border_width = 2
outer_border_width = 0
corner_radius = 16
drag_opacity = 0.8

[appearance.blur]
enabled = false

[appearance.shadow]
enabled = false