[environment]
CURSOR_SIZE = "36"
CURSOR_THEME = "Bibata-Modern-Catppuccin-Mocha-Blue"
QT_QPA_PLATFORMTHEME = "qt6ct"
SDL_VIDEO_DRIVER = "wayland"
XCURSOR_SIZE = "36"
XCURSOR_THEME = "Bibata-Modern-Catppuccin-Mocha-Blue"