[input]
client_window_drag = false
middle_click_paste = false
window_drag_toggle = "none"

[input.keyboard]
layout = "us,ru"
numlock_toggle = false
options = "caps:none"
repeat_delay = 500
repeat_rate = 25
track_layout = "global"

[input.touchpad]
accel_profile = "flat"
disable_while_typing = false
left_handed = false
natural_scroll = true
scroll_factor = 1
sensitivity = 1
tap = true

[input.mouse]
accel_profile = "flat"
natural_scroll = false
scroll_wheel_step = 60
sensitivity = 0

[[input.device]]
accel_profile = "flat"
name = "INSTANT USB GAMING MOUSE "
sensitivity = -0.7

[input.cursor]
follows_focus = false
hardware_cursor = false
hide_timeout_ms = 5000
hide_when_typing = false
size = 36
theme = "Bibata-Modern-Catppuccin-Mocha-Blue"

[input.focus]
follows_mouse = true
follows_mouse_max_scroll = 0.5