# Umbriel `layout` config file

[layout]
extent_presets = [0.25, 0.50, 0.75, 1.0]
gap = 16
mode = "scrolling"

[layout.struts]
bottom = 0
left = 0
right = 0
top = 0

[layout.scrolling]
center_underfull_strip = false
default_extent_fraction = 0.5