# Window
[[window_rule]]
default_maximize = true
match.is_alone = true

[[window_rule]]
blur = false
blur_optimized = false

[[window_rule]]
tearing = true

[[window_rule]]
match.is_focused = true
opacity = 1

[[window_rule]]
match.is_focused = false
opacity = 0.95

# Apps
[[window_rule]]
default_floating = true
match.app_id = "org.gnome.Calculator"

[[window_rule]]
default_maximize = true
match.app_id = "vesktop"

[[window_rule]]
default_maximize = true
default_workspace = 2
match.app_id = "zen"

[[window_rule]]
default_maximize = true
match.app_id = "dev.noctalia.Noctalia"

[[window_rule]]
default_fullscreen = true
default_workspace = 1
match.app_id = "Minecraft 1.8.9"

[[window_rule]]
default_maximize = true
match.app_id = "com.ktechpit.whatsie"

[[window_rule]]
default_maximize = true
match.app_id = "blender"

[[window_rule]]
default_maximize = true
match.app_id = "org.gnome.Boxes"

[[window_rule]]
default_maximize = true
match.app_id = "org.telegram.desktop"

[[window_rule]]
default_maximize = true
match.app_id = "Spotify"

[[window_rule]]
default_fullscreen = true
match.app_id = "org.vinegarhq.Sober"

[[window_rule]]
default_maximize = true
match.app_id = "com.obsproject.Studio"

[[window_rule]]
default_maximize = true
match.app_id = "steam_proton"

[[window_rule]]
default_floating = true
match.app_id = "PortProton"

[[window_rule]]
default_maximize = true
match.app_id = "io.github.elyprismlauncher.ElyPrismLauncher"

[[window_rule]]
default_maximize = true
match.app_id = "code"

[[window_rule]]
default_maximize = true
match.app_id = "obsidian"

[[window_rule]]
default_maximize = true
match.app_id = "viber"

[[window_rule]]
default_floating = true
default_floating_size_px = {width = 800, height = 500}
match.app_id = "dev.noctalia.UmbrielSharePicker"

[[window_rule]]
default_floating = true
default_floating_size_px = {width = 800, height = 500}
match.app_id = "xdg-desktop-portal-gtk"